### ISSUE TITLE
Ability to ignore "Component isn't from library" if the current file is a library

### ISSUE THREAD

**Issue by websiddu** [destefanis/design-lint#1]
Currently when working on a figma file that is published as a design system the components will not be the root and will not originate from library. 

The "Component isn't from library" should be ignored if the file is library.

**Comment by destefanis** [comment]
I'm actually going to remove this check for now and consider having it as a configurable toggle. I commented it out in the code and left it with some notes that way it can serve as an example of how to add custom rules.
