### ISSUE TITLE
Avoid running auto-refresh when Figma file is in the background

### ISSUE THREAD

**Issue by alexjlockwood** [destefanis/design-lint#17]
The plugin currently auto-refreshes in the background, even when Figma is minimized or a different Figma file tab is being used.

In addition to triggering auto-refresh when the window state changes from 'focus' to 'blur', I found it useful to also take the document's visibility into account as well (i.e. don't auto-refresh when `document.hidden` is true): https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event

**Comment by destefanis** [comment]
Resolved in the latest release
