### ISSUE TITLE
Idea for Improvement

### ISSUE THREAD

**Issue by faridsabitov** [destefanis/design-lint#3]
Hi Daniel
Thank you for sharing your plugin.

I started to use that on my daily process and I faced some "process" problems. But first, I would like to give some background information, so you will know more details.

**Use Case:** I want to check only the local components. To organize everything we are using another library https://www.figma.com/c/file/788676139164058166 and there I have some issues. Can I have some kind of checkbox or ability to ignore all components from a specific library? So I can lint designs for the library that I'm working on right now?

**Suggestion:** There are two touchpoints for this feature. The one on the "review" screen. We can add a menu icon with drop-down options like "ignore component" or "ignore library". Here is the preview https://tppr.me/Rkbec and the second touchpoint on the settings page. Where I can add connected libraries as ignored.

If you would like to have a quick call, here is my [calendly.com/faridsabitov](https://calendly.com/faridsabitov). Thank you for helping the design community!

All the best,
Farid

**Comment by destefanis** [comment]
Hey Farid!

This is a great idea. Unfortunately, Figma API doesn't support knowing anything about specific libraries. One solution could be if a component is not "remote" (which means from a separate file) it could ignore it. This is a bit more specific than I think most people need, but I could help you build it or add it to a larger suggestions list? I'm going to close this issue for now and add it to a larger issue for suggestions!
