### ISSUE TITLE
Linting figma tokens

### ISSUE THREAD

**Issue by phantasmagoriadigital** [destefanis/design-lint#36]
Just found your plugin. We actually just started building something similar, but with the goal to:

Check all components, layer by layer and verify if all values that can be a figma token are set. 

 All values that are not set with a token, show the nearest matching tokens and option to apply missing tokens easily. 

Convert all styles to matching tokens.

I'm hoping something on these lines has already been created, if not, with some guidance we'd be happy to contribute this functionality. I thi k this makes a lot of sense for many teams.

**Comment by destefanis** [comment]
I do agree that would be great! But two problems come to mind:
1. Unless something has changed, the only way to import styles is if their local (meaning all the styles need to be in the figma document the Design Lint is running in) *unless* the plugin has access to the library of the team (this requires the plugin to be private).
2. Second, we would need some form of "what the closest" option is, which would require some curation I think.

Your best bet is to fork this and make it private, that way you can access your teams library of tokens. Then you could probably make recommendations off of a few things: node (layer) type, properties like font or where a hexcolor is in a spectrum etc.

So as for an actual feature I don't think its possible for public release, but definitely for private!
