### ISSUE TITLE
Errors resolving without being solved.

### ISSUE THREAD

**Issue by Subcide** [destefanis/design-lint#6]
Just had this issue, where a bunch of errors were found, then when I jump to the first error, they all magically resolve.  I don't have any rules ignored in settings.  They are on instances of components if that matters at all.

![Screen-Recording-2020-01-30-at-09 02 58](https://user-images.githubusercontent.com/272365/73436125-d42ee600-4341-11ea-9038-85233b853b9d.gif)

**Comment by destefanis** [comment]
Interesting. I do have some logic around ignoring hidden fills (there are a few reasons people do this, usually components or layers that aren't always visible).

@Subcide could you create a community page or upload this ui to a figma file so I can test this on my own? The smaller badges are for "errors found below", do those instances have child layers? Hard to tell what's happening without having it handy.
